/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.1 Update 1
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2017 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "Bootloadable.h"
#include "ECG_ADC_In_aliases.h"
#include "ECG_ADC_In.h"
#include "ECG_ADC.h"
#include "Timer_Clock.h"
#include "ECG_ADC_Delay_Timer.h"
#include "Sample_Clock.h"
#include "ECG_ADC_EOC_ISR.h"
#include "ECG_ADC_REF_DAC.h"
#include "ECG_MuxControl_N_aliases.h"
#include "ECG_MuxControl_N.h"
#include "ECG_MuxControl_P_aliases.h"
#include "ECG_MuxControl_P.h"
#include "ADC_DMA_dma.h"
#include "PB1_aliases.h"
#include "PB1.h"
#include "LED0_aliases.h"
#include "LED0.h"
#include "LED1_aliases.h"
#include "LED1.h"
#include "ECG_Mux_P_ENB_aliases.h"
#include "ECG_Mux_P_ENB.h"
#include "ECG_Mux_N_ENB_aliases.h"
#include "ECG_Mux_N_ENB.h"
#include "ECG_RL_DRIVE_DAC.h"
#include "ECG_REF_DRIVE_DAC.h"
#include "ECG_RL_DRIVE_aliases.h"
#include "ECG_RL_DRIVE.h"
#include "ECG_REF_DRIVE_aliases.h"
#include "ECG_REF_DRIVE.h"
#include "BT_RESETn_aliases.h"
#include "BT_RESETn.h"
#include "BT_GPIO7_aliases.h"
#include "BT_GPIO7.h"
#include "BT_GPIO6_aliases.h"
#include "BT_GPIO6.h"
#include "BT_UART_RTS_aliases.h"
#include "BT_UART_RTS.h"
#include "BT_UART_CTS_aliases.h"
#include "BT_UART_CTS.h"
#include "BT_GPIO3_aliases.h"
#include "BT_GPIO3.h"
#include "BT_GPIO4_aliases.h"
#include "BT_GPIO4.h"
#include "BT_UART.h"
#include "USBUART.h"
#include "USBUART_audio.h"
#include "USBUART_cdc.h"
#include "USBUART_hid.h"
#include "USBUART_midi.h"
#include "USBUART_pvt.h"
#include "USBUART_cydmac.h"
#include "USBUART_msc.h"
#include "ECG_REF_ADC.h"
#include "ECG_REF_ADC_EOC_ISR.h"
#include "ECG_ADC_REF_DAC_SET_ISR.h"
#include "BT_RECEIVE_ISR.h"
#include "ECG_ADC_Ext_CP_Clk.h"
#include "ECG_ADC_IRQ.h"
#include "ECG_ADC_theACLK.h"
#include "BT_UART_IntClock.h"
#include "USBUART_Dm_aliases.h"
#include "USBUART_Dm.h"
#include "USBUART_Dp_aliases.h"
#include "USBUART_Dp.h"
#include "ECG_REF_ADC_IRQ.h"
#include "ECG_REF_ADC_theACLK.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"

/*[]*/

